voxpupuli/puppet-powerdns

README.md
manifests/init.pp
manifests/params.pp

We use our own repo installation and would like to be able to disable repo installation.

Support to disable repo installation and use custom repo

---

README.md
manifests/authoritative.pp
manifests/backends/mysql.pp
manifests/config.pp
manifests/init.pp
manifests/params.pp
manifests/repo.pp
metadata.json
spec/acceptance/class_spec.rb
spec/classes/powerdns_init_spec.rb

Spelling Fix

---

Gemfile
manifests/backends/mysql.pp
manifests/init.pp
manifests/params.pp
spec/classes/powerdns_init_spec.rb
spec/spec_helper.rb

Also update some Gemfile versions now that puppet 3 (and older rubies)
aren't supported.

Convert to puppet 4+ data types

---

Gemfile
manifests/backends/mysql.pp
manifests/init.pp
manifests/params.pp
spec/classes/powerdns_init_spec.rb
spec/spec_helper.rb

This wasn't supposed to go into master.

Revert "Convert to puppet 4+ data types"

---

manifests/backends/mysql.pp
spec/acceptance/class_spec.rb
spec/classes/powerdns_init_spec.rb

This whould close #19 and #31.

Set gmysql-host in powerdns::mysql

---

.fixtures.yml
metadata.json

This PR upgrades all dependencies.

Upgrade dependencies

---

manifests/backends/mysql.pp
manifests/init.pp
manifests/params.pp
spec/classes/powerdns_init_spec.rb

Hello!
This adds an option to make the database port configurable.
Best regards,
Stefan

add an option to make the database port configurable

---

.fixtures.yml
.github/workflows/main.yml
Gemfile
metadata.json

Closes #82, closes #83, closes #84

Add support for Puppet 7

---

manifests/init.pp

Nothing special within the changelogs and the module is managing 4.4 with my 4.3 config

add 4.4 as supported version

---

manifests/repo.pp

authoritative and recursor package should depend on apt repo, fixes #90

---

README.md
manifests/init.pp
manifests/params.pp
spec/classes/powerdns_init_spec.rb

Fix RedHat sqlite schema file

---

README.md
manifests/init.pp
manifests/params.pp
spec/classes/powerdns_init_spec.rb

Reverts sensson/puppet-powerdns#98

chore: revert unfinished bugfix

---

.github/workflows/main.yml

This allows switching to the main branch only

Run actions on push to any branch or pull requests

---

metadata.json

Adds support for postgresql < 9.0.0

Allow postgresql 8 module

---

lib/puppet/type/powerdns_zone.rb
lib/puppet/type/powerdns_zone_private.rb

allow using puppet generate types

---

manifests/init.pp
manifests/params.pp

Every value in the params.pp sets the param to true, so we can simplify this by moving the value to init.pp

backend_install: default to true in init.pp

---

manifests/params.pp
manifests/repo.pp
metadata.json
spec/classes/powerdns_init_spec.rb
spec/defines/powerdns_config_spec.rb

also contains:
* #154
* #156 
* #152 
* #153 
* #157 
* #158
* #155 
* #151

Add Arch Linux support

---

.github/workflows/main.yml
metadata.json

Support Puppet 8 & updated CI workflow.

Puppet 8 support

---

templates/forward_zones.conf.erb

Update forward_zones.conf.erb to remove .sort

---

metadata.json

Please merge https://github.com/sensson/puppet-powerdns/pull/178 before

Remove eol centos

---

metadata.json

Please merge https://github.com/sensson/puppet-powerdns/pull/178 before

Remove eol oraclelinux

---

manifests/params.pp
manifests/repo.pp
metadata.json

Please merge https://github.com/sensson/puppet-powerdns/pull/178 before

Remove eol redhat

---

Rakefile

modulesync 10.0.0

---

HISTORY.md

add HISTORY.md

---

REFERENCE.md
data/common.yaml
data/os/FreeBSD.yaml
data/os/RedHat.yaml
manifests/authoritative.pp
manifests/backends/sqlite.pp
manifests/init.pp
manifests/recursor.pp
spec/classes/powerdns_init_spec.rb

set proper permissions on config files, fixes #221
