README.md
manifests/init.pp

I need to overwrite it to 'select account from supermasters where ip=\'%s\' and nameserver=\'%s\'' to make it work for version 4.0.1

Be able to overwrite supermaster_query

---

manifests/init.pp

If you setup in hiera recursor config which is also read by an authoritive only node it fails to apply it.
```
Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: File_line[powerdns-config-forward-zones-example.net=1.2.3.253-/etc/powerdns/recursor.conf] { before => Service[pdns-recursor] }, because Service[pdns-recursor] doesn't seem to be in the catalog
```
So let's look it up only if we want to.

Only try to set config if we want to the corresponding services

---

manifests/init.pp

Documentation (and expected results) specify that db_root_password is
required if backend_install is true. Modify init.pp to only fail if
authoritative AND backend_install is true.
This is in reference to #10

Change basic check to look at backend_install

---

manifests/config.pp
metadata.json
spec/defines/powerdns_config_spec.rb

Support removing config with `ensure => absent`.  In a separate commit I've converted the class to use puppet 4 style parameter validation.

Support purging config settings

---

manifests/init.pp

The 'private' subclasses should really be contained to help with
ordering.
eg I was doing something a bit like...
```puppet
pulp_rpmbind{'powerdns-4.1':}
class { 'powerdns':
custom_repo => true,
require     => Pulp_rpmbind['powerdns-4.1'],
...
}
```
But since powerdns::authoritative wasn't 'contained' in init.pp the
ordering I was trying to enforce didn't work as expected.  I ended up
with powerdns installed from EPEL.

Contain subclasses in init.pp

---

README.md
manifests/backends/mysql.pp
manifests/init.pp
manifests/params.pp
spec/classes/powerdns_init_spec.rb

When set to false, the backend tables won't be managed.
Defaults to true so is backwards compatible.
This is useful if your database is on another host.  It will
also make adding basic postgresql support easier.

Add backend_create_tables parameter

---

README.md
manifests/params.pp
manifests/repo.pp
metadata.json

Instead of supporting just CentOS, support all RedHat family OSes.

Support other RedHat flavours

---

manifests/repo.pp

Added the full fingerprint to eliminate the apt class warning "The id should be a full fingerprint (40 characters)".

Update id to be a full fingerprint.

---

manifests/authoritative.pp
manifests/backends/ldap.pp
manifests/init.pp
manifests/params.pp
spec/classes/powerdns_init_spec.rb

For another project I use OpenLDAP as backend with PowerDNS and as such quickly added some basic LDAP backend support to this module. It does not depend on any OpenLDAP puppet module from the forge as unfortunately there are none which are really actual and/or working properly. So it's up to the ops to install and configure OpenLDAP and not this module unlike for the MySQL and PostgreSQL backend.
Unit tests all pass and I tested UAT for debian9, centos7 and ubuntu1604 which also pass.
Btw thanks for release 1.3.0 of this module yesterday :+1: I was looking forward that one...

Add basic LDAP backend support

---

manifests/backends/postgresql.pp
spec/classes/powerdns_init_spec.rb

I found out that when using the pdns-server and pdns-backend-pgsql packages from the official Debian APT repository instead of the default PowerDNS APT repo by setting `custom_repo = true` param there are two issues:
* The pdns-server package from Debian automatically install the pdns-backend-bind package.
* The pdns-backend-pgsql package from Debian automatically configures some default configuration using debconf for this backend in the `/etc/powerdns/pdns.d/pdns.local.gpgsql.conf` file.
This PR ensures that the `/etc/powerdns/pdns.d/pdns.local.gpgsql.conf` file gets deleted and that the package pdns-backend-bind gets purged along with its default config file when using Debian. This allows the PowerDNS PostgreSQL backend pacakge to be used from the Debian APT repo directly instead of …

Remove bind backend pkg and pgsql config when using Debian repo

---

manifests/init.pp
manifests/params.pp
manifests/repo.pp
spec/classes/powerdns_init_spec.rb

Is there a reason for not supporting powerdns 4.2 yet?
I've tested on centos 7 , and it seems to simply work without any further changes.
Debian-Repositories also exist, with used naming-scheme for version 4.2

also support version 4.2 of powerdns and set as default

---

manifests/init.pp
manifests/repo.pp

Using a pattern for version checking is shorter than listing every
version. A case with a default fail is not needed. A regsubst is more
efficient and supported versions are already checked in init.pp

add support for PDNS 4.3 and refactor data type and support case

---

metadata.json

This PR bumps the apt puppet forge module dependency from 7.0.0 to 7.6.0 as requested in issue #77.

Bump apt dependency to 7.6.0

---

manifests/config.pp

This fixes #76 
This module is capable of managing powerdns 4.1/4.2 e.g. on Ubuntu Bionic or Focal

allow local-ipv6 to be empty, fixes #76

---

manifests/backends/ldap.pp
manifests/backends/mysql.pp
manifests/backends/postgresql.pp
manifests/backends/sqlite.pp

When upgrading PDNS the backend package is not upgraded to the correct version, resulting in PDNS not starting.
This commit aim to fix this behaviour. By default, the packages_ensure remains `installed` as of now, but it can be tweeked to reflect changes to the pdns package.

Use package_ensure on backends' packages

---

manifests/repo.pp
spec/classes/powerdns_init_spec.rb

If the OS name is Rocky the Rocky linux mirrors.rockylinux.org should be used.

Use the Rocky Linux mirrorlist when the OS name is Rocky

---

manifests/repo.pp

Hello,
If an `ensure_packages('yum-plugin-priorities')` is already declared, that fail because the class declare some params. `installed` is the default value and I've split the ordering.
Regards,

fix bug duplicate resource yum-plugin-priorities

---

README.md
lib/puppet/provider/powerdns_zone_private/pdnsutil.rb
lib/puppet/type/powerdns_record.rb
lib/puppet/type/powerdns_zone.rb
lib/puppet/type/powerdns_zone_private.rb
manifests/authoritative.pp
manifests/backends/bind.pp
manifests/backends/ldap.pp
manifests/backends/mysql.pp
manifests/backends/postgresql.pp
manifests/backends/sqlite.pp
manifests/config.pp
manifests/recursor.pp
spec/acceptance/class_spec.rb
spec/classes/powerdns_init_spec.rb
spec/defines/powerdns_config_spec.rb
spec/unit/puppet/provider/powerdns_zone_private/pdnsutil_spec.rb
spec/unit/puppet/type/powerdns_record_spec.rb
spec/unit/puppet/type/powerdns_zone_private_spec.rb
spec/unit/puppet/type/powerdns_zone_spec.rb

allow managing zones and records with puppet for a specific zone.
The service name change commit simplifies the autorequire dependencies.

allow to manage zones and records (with opt out) with puppet 

---

lib/puppet/provider/powerdns_zone_private/pdnsutil.rb
lib/puppet/type/powerdns_zone.rb
lib/puppet/type/powerdns_zone_private.rb

In certain cases (noted on SOA and NS) records there was an update
on each puppet run. We now sort the pdnsutil output the same way
as we do for the input to avoid this problem.
This is a fix to the merge request #122

sort pdnsutil output to avoid update on each puppet run

---

.pmtignore

Inspired by https://github.com/puppetlabs/puppet-modulebuilder/blob/main/lib/puppet/modulebuilder/builder.rb#L8-L17
Fix #127

Ignore .git for pdk build

---

manifests/init.pp
spec/classes/powerdns_init_spec.rb

At least recursor is stable in 4.7 version. Generally from maintainer's perspective I'd say it's easier to allow any version number matching certain format. Otherwise you should maintain whole compatibility matrix for all distributions and release versions which is painful :disappointed:

Support 4.7 release

---

Gemfile
manifests/config.pp
spec/defines/powerdns_config_spec.rb
spec/spec_helper_acceptance.rb

Many configuration parameters have `Boolean` type. This PR allows passing booleans with no need to write them as `String`.

Allow passing boolean

---

README.md
manifests/authoritative.pp
manifests/init.pp
manifests/params.pp
manifests/recursor.pp
spec/classes/powerdns_init_spec.rb
templates/forward_zones.conf.erb

Forward zones configuration is a bit messy when too many domains are on a single line:
```
forward-zones=example.org=203.0.113.210, powerdns.com=2001:DB8::BEEF:5
```
this PR adds possibility to zones as a hash:
```yaml
powerdns::forward_zones:
example.org: 203.0.113.210
powerdns.com: 2001:DB8::BEEF:5
```

Support configuration of multiple forward zones

---

manifests/authoritative.pp
manifests/init.pp
manifests/params.pp
manifests/recursor.pp

Puppet will figure out the provider on it's own. It's not required to configure it. Cleaning this up will make it easier to implement new operating systems.

Drop unneeded service_provider name

---

manifests/backends/mysql.pp
spec/classes/powerdns_init_spec.rb

As of Mysql module 13.0.0 mysql::db sql parameter can only be an array

mysql::db sql parameter changed to array

---

manifests/backends/mysql.pp
manifests/backends/postgresql.pp
manifests/init.pp
spec/classes/powerdns_init_spec.rb

At least for postgresql it's not required that the database_user has a password.

make gpgsql-password optional

---

.github/workflows/test.yml
README.md
manifests/backends/ldap.pp
manifests/backends/mysql.pp
manifests/backends/postgresql.pp
manifests/config.pp
manifests/init.pp
spec/classes/powerdns_init_spec.rb
spec/defines/powerdns_config_spec.rb
types/configvalue.pp
types/secret.pp

This PR adds support secrets passed as [Sensitive](https://www.puppet.com/docs/puppet/7/lang_data_sensitive.html) data type.

Support Sensitive strings

---

manifests/backends/postgresql.pp

fixes:
Evaluation Error: Error while evaluating a Function Call, deprecation. postgresql_password. This method is deprecated, please use postgresql::postgresql_password instead

Bugfix: fix deprecated use of postgresql_password()

---

metadata.json

Allow `puppetlabs/postgresql` versions `10.0.x`

Allow postgresql 10 module

---

README.md
manifests/authoritative.pp
manifests/backends/lmdb.pp
manifests/init.pp
manifests/params.pp
spec/classes/powerdns_init_spec.rb

This PR adds support for the lmdb backend of pdns. I have conformed to the "params" method of supplying configuration options, to let it blend in with the rest.

Add lmdb backend option

---

manifests/backends/postgresql.pp
metadata.json

- Ubuntu 24.04
- PostgreSQL 16
I faced permissions issue that leads to:
- failed schema application
- issuficient priviledges for further changes from powerdns
I've fixed it manually by doing these queries:
```sql
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO powerdns;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO powerdns;
```
Then I diged dipper to find how to puppetize them and came to that solution (making powerdns user an owner of powerdns db). 
If it looks dangerous it may be fixed by adding these resources:
```puppet
#
postgresql::server::default_privileges { 'all-tables':
role        => $powerdns::db_username,
db          => $powerdns::db_name,
privilege   => 'ALL',
object_type => 'TABLES',
schema      => 'public',
require     => Class['postgresql::server'],
} …
```

PostgreSQL backend: make powerdns a database owner

---

manifests/repo.pp

The current regex to get the short repo version isn't matching correctly. This PR fixes the issue.
See https://regex101.com/r/dRrY85/1 for more details.

fix regex to get repo version

---

manifests/repo.pp

I don't know why, but the authoritative APT source contains the `pdns-recursor` package, which makes it impossible to have different versions installed.

pin recursor apt source with higher priority

---

data/common.yaml
spec/acceptance/class_spec.rb
spec/classes/powerdns_init_spec.rb

Otherwise, tests are failing on Ubuntu 24.04, as the upstream repo isn't available

update recursor version to 5.0, authoritative version to 4.9

---

data/os/Debian/11.yaml
data/os/RedHat.yaml
manifests/backends/mysql.pp
manifests/init.pp
metadata.json

charset and collate will be set for some supported OSes, as otherwise acceptance tests are failing due to corrective changes, see https://github.com/puppetlabs/puppetlabs-mysql/issues/1639

allow puppetlabs/mysql 16.X

---

data/os/RedHat.yaml
manifests/authoritative.pp
manifests/init.pp
spec/classes/powerdns_init_spec.rb

The permissions on the `/etc/pdns/pdns.conf` file do not allow the service to read it when using the standard pdns user on Rocky9. 
This PR changes the permissions on the file such that the pdns service can read, but not write to it. This allows the service to start correctly.
There were originally other changes in this PR, however, they have been merged and are now nolonger needed.

correct pdns.conf permissions on Redhat derivatives

---

lib/puppet/type/powerdns_zone.rb

The messages for many of the parameters on the powerdns_zone primitive were copied from the config_dir message and referenced that parameter by name. This updates each error to explicitly reference the correct parameter to reduce opportunities for confusion.

fix: parameter type error messages
